### ISSUE TITLE
docker compose

### ISSUE THREAD

**Issue by drewelliott** [srl-labs/netbox-nrx-clab#5]
Invalid Plugins:
  compose     failed to fetch metadata: fork/exec /home/drew/.docker/cli-plugins/docker-compose: ex
ec format error

This is on an Ubuntu 22.04 LTS server -

For the workaround, I had to edit 3_deploy_netbox.sh to change the command to `docker-compose` instead of `docker compose` - just something to keep in mind

**Comment by hellt** [comment]
This is somewhat expected. I think you installed docker via Ubuntu packages? This would install an older docker version where the compose is not a subcommand

**Comment by drewelliott** [comment]
yes, you are correct - I changed and updated to not use the ubuntu packages and now it is working correctly - closing
